### ISSUE TITLE
crash when network status changes

### ISSUE THREAD

**Issue by yonahforst** [Apercu/react-native-zeroconf#12] opened 2016-06-15 10:46 UTC
I find that when I toggle wifi on/off while scanning, my app crash.

For some reason, this causes the `service` to become nil and crashes when it tries to set a nil key in a dictionary 

![screen shot 2016-06-15 at 12 45 38](https://cloud.githubusercontent.com/assets/1440796/16077115/266611a0-32f7-11e6-84f1-4df1d9924378.png)

**Comment by Apercu** [comment] 2016-06-15 11:34
Thanks for the report! Will investigate on this.

**Comment by Apercu** [comment] 2016-06-29 14:41
Just an update to inform I've had difficulties to find an stable OSX system lately to sort this out, but I've not forgotten you ;)

**Comment by Apercu** [comment] 2016-07-24 09:45
Hi @yonahforst, I can't manage to reprod using the latest version.
When running on my device and discovering a service, I toggle my wifi, the service is resolved again and no error occurs.

Could you please try it out?

**Comment by westcode** [comment] 2016-09-22 14:48
Hi @Apercu I have exactly the same error as described above, but i receive it immediately after starting a scan (no switching of networks). Any idea?

**Comment by westcode** [comment] 2016-09-22 16:14
The issue seems to occur when .scan() is called multiple times (stopping/starting) -> the callback is called with an empty service?

**Comment by Apercu** [comment] 2016-09-22 16:18
Hum that's strange, do you have any stacktrace?

**Comment by westcode** [comment] 2016-09-26 08:09
This is the HockeyApp report [faa57cb0db352ab7e98969fb1eaeada7.log.txt](https://github.com/Apercu/react-native-zeroconf/files/492542/faa57cb0db352ab7e98969fb1eaeada7.log.txt)

**Comment by hubertperron** [comment] 2017-01-13 15:38
I happen to have the same problem. I'm stopping and starting the the scan every 10 seconds and sometime it crash.

I have played with the interval timeout and I can get it to crash reliably if I set the timeout to something excessive like 500ms.

Here's the stacktrace:

```
2017-01-13 10:30:21.128 tekapp[39212:7467335] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f866d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e6ea21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f7fede3 -[__NSDictionaryM removeObjectForKey:] + 675
	3   tekapp                              0x000000010de8188a -[RNZeroconf netServiceBrowser:didFindService:moreComing:] + 378
	4   CFNetwork                           0x000000010f28c492 -[NSNetServiceBrowser _dispatchCallBack:flags:error:] + 995
	5   CFNetwork                           0x000000010f1d6cc7 _ZL14_BrowserCancelP21__CFNetServiceBrowser + 133
	6   CoreFoundation                      0x000000010f80b761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x000000010f7f098c __CFRunLoopDoSources0 + 556
	8   CoreFoundation                      0x000000010f7efe76 __CFRunLoopRun + 918
	9   CoreFoundation                      0x000000010f7ef884 CFRunLoopRunSpecific + 420
	10  GraphicsServices                    0x00000001156dca6f GSEventRunModal + 161
	11  UIKit                               0x0000000111dfbc68 UIApplicationMain + 159
	12  tekapp                              0x000000010dce4fcf main + 111
	13  libdyld.dylib                       0x00000001137d068d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Apercu** [comment] 2017-01-13 18:24
Thanks for this one, it appears more clearly that I comes from [here](https://github.com/Apercu/react-native-zeroconf/blob/develop/ios/RNZeroconf/RNZeroconf.m#L42). Would you be able to breakpoint into this to check wether it happens because the service name is `nil` or more generally what the `service` object look like?

**Comment by Apercu** [comment] 2017-01-23 19:16
Have you tried to specify a error handler as stated by @jdpigeon in #23? It might fix the crash.

**Comment by Apercu** [comment] 2017-03-25 21:14
Landed a change in `0.8.0` that might fix the issue. Please try and get back to me :)

**Comment by hubertperron** [comment] 2017-03-27 19:37
Just upgraded and it seems like the problem is fixed 👍

**Comment by Apercu** [comment] 2017-04-12 06:04
Closing this one as it seems to be resolved by the latest release.

**Closed by Apercu** 2017-04-12 06:04 UTC
Labels: bug
